import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

export const translations = {
  bn: {
    // Brand & App
    appName: 'Tasker',
    appBadge: 'সার্বজনীন',
    searchPlaceholder: 'টাস্ক সার্চ করুন...',
    aiChat: 'AI চ্যাট',
    storageMode: 'স্টোরেজ মোড',
    zeroCostStorage: '● লোকাল ও P2P (খরচ শূন্য)',
    storageDesc: 'ফাইল ক্লাউডে নয়, আপনার পিসিতে নিরাপদে সংরক্ষিত।',

    // Sidebar
    mainNavigation: 'প্রধান মেনু',
    workDashboard: 'ওয়ার্ক ড্যাশবোর্ড',
    currentWorkspace: 'বর্তমান কাজের বোর্ড',
    calendarView: 'ক্যালেন্ডার ভিউ',
    calendarSub: 'তারিখভিত্তিক কাজের হিসাব',
    people: 'পিপল (People)',
    peopleSub: 'কানেক্টেড ইউজার ও নেটওয়ার্ক',
    myTeam: 'আমার টিম',
    teamSub: 'সহযোগিতা ও রিকোয়েস্ট',
    community: 'কমিউনিটি',
    communitySub: 'গ্লোবাল নেটওয়ার্ক চ্যাট',
    clientDictionary: 'ক্লায়েন্ট ডিকশনারি',
    clientSub: 'ক্লায়েন্ট ও কাজের হিসাব',
    taskDirectory: 'টাস্ক ডিরেক্টরি',
    taskDirectorySub: 'ব্যক্তিগত ও টিমভিত্তিক টাস্কের ধরন',

    // Dashboard
    personal: 'ব্যক্তিগত',
    team: 'টিম',
    selectTeam: 'টিম নির্বাচন:',
    allTeamsOption: 'সকল টিম',
    kanban: 'কানবান',
    list: 'লিস্ট',
    filterBy: 'ফিল্টার:',
    allClients: 'সকল ক্লায়েন্ট',
    allCategories: 'সকল টাস্ক টাইপ',
    allTaskTypes: 'সকল টাস্ক টাইপ',
    reset: 'রিসেট',
    newTask: 'নতুন টাস্ক',
    todo: 'করতে হবে (To Do)',
    inProgress: 'চলমান (In Progress)',
    submitForReview: 'রিভিউ জমা (Submit for Review)',
    approved: 'অনুমোদিত (Approved)',
    done: 'সম্পন্ন (Done)',
    startWork: 'কাজ শুরু করুন',
    markDone: 'সম্পন্ন',
    submitReviewBtn: 'রিভিউতে পাঠান',
    approveBtn: 'অনুমোদন দিন',
    carryForward: 'পরবর্তী তারিখে নিন (Carry Forward)',
    sendBackTodo: 'To Do-তে ফেরত পাঠান',
    sendBackInProgress: 'In Progress-এ ফেরত পাঠান',
    editTask: 'টাস্ক এডিট করুন',
    deleteTask: 'টাস্ক মুছুন',
    moveToTeam: 'টিমে নিন',
    moveToPersonal: 'ব্যক্তিগতে নিন',
    noTasksInCol: 'এই কলামে কোনো কাজ নেই',
    noTasksFound: 'কোনো টাস্ক পাওয়া যায়নি। "নতুন টাস্ক" বাটনে ক্লিক করুন।',
    taskTitleCol: 'কাজের নাম',
    clientCategoryCol: 'ক্লায়েন্ট / টাস্ক টাইপ',
    clientTaskTypeCol: 'ক্লায়েন্ট / টাস্ক টাইপ',
    dateCol: 'তারিখ',
    priorityCol: 'অগ্রাধিকার',
    actionsCol: 'অ্যাকশন',
    selectCarryForwardDate: 'কাজের নতুন তারিখ নির্বাচন করুন:',

    // Task Modal
    createTaskModalTitle: 'নতুন টাস্ক তৈরি',
    editTaskModalTitle: 'টাস্ক এডিট করুন',
    taskTitleLabel: 'টাস্কের শিরোনাম *',
    taskTitlePlaceholder: 'কী কাজ করতে হবে লিখুন বা ভয়েস দিন...',
    scheduledDateLabel: 'কাজের তারিখ',
    workspaceLabel: 'ওয়ার্কস্পেস',
    teamLabel: 'টিম নির্বাচন করুন',
    briefLabel: 'বিস্তারিত বিবরণ',
    briefPlaceholder: 'টাস্কের বিস্তারিত নোট বা নির্দেশনা লিখুন...',
    sourceLinkLabel: 'সোর্স লিংক (Figma / GitHub / Link)',
    clientTagLabel: 'ক্লায়েন্ট ট্যাগ করুন',
    noClientOption: '-- কোনো ক্লায়েন্ট নেই --',
    categoryLabel: 'টাস্ক টাইপ',
    taskTypeLabel: 'টাস্ক টাইপ',
    noCategoryOption: '-- সাধারণ / কোনোটি নয় --',
    noTaskTypeOption: '-- সাধারণ / কোনোটি নয় --',
    priorityLabel: 'অগ্রাধিকার',
    priorityLow: 'স্বাভাবিক (Low)',
    priorityMedium: 'সাধারণ (Medium)',
    priorityHigh: 'গুরুত্বপূর্ণ (High)',
    priorityUrgent: 'জরুরি (Urgent)',
    fileAttachLabel: 'ফাইল ও ছবি যুক্ত করুন (লোকাল পিসিতে সংরক্ষিত হবে)',
    cancel: 'বাতিল',
    saveTask: 'টাস্ক সেভ করুন',
    updateTask: 'টাস্ক আপডেট করুন',
    voiceHoldText: 'চেপে ধরে কথা বলুন',
    voiceRecording: 'রেকর্ড হচ্ছে...',
    voiceReleaseDone: 'ছেড়ে দিলে সম্পন্ন হবে',
    slideCancel: 'বাতিল করতে স্লাইড করুন',

    // Calendar
    today: 'আজকের দিন',
    todayBadge: 'আজ',
    sun: 'রবি', mon: 'সোম', tue: 'মঙ্গল', wed: 'বুধ', thu: 'বৃহঃ', fri: 'শুক্র', sat: 'শনি',
    completedCount: 'সম্পন্ন',
    pendingCount: 'বাকি',
    pastHistoryTitle: 'পূর্বের কাজের হিস্ট্রি',
    todayTitle: 'আজকের কাজ',
    futurePlanTitle: 'ভবিষ্যতের পরিকল্পনা',
    addTaskOnDate: 'কাজ যোগ করুন',
    // People & Contacts
    peopleTitle: 'পিপল ও কানেক্টেড নেটওয়ার্ক',
    peopleSubtitle: 'গ্লোবাল ইউজার খুঁজুন, কানেক্ট করুন, টিমে যুক্ত করুন বা ক্লায়েন্টের Contact Person হিসেবে ট্যাগ করুন।',
    searchPeoplePlaceholder: 'নাম বা ইউজারনেম দিয়ে নতুন ব্যক্তি খুঁজুন...',
    connectedPeopleTitle: 'কানেক্টেড ব্যক্তিবর্গ',
    noConnectedPeople: 'এখনও কোনো ইউজার কানেক্ট করা হয়নি। উপরের সার্চ থেকে ইউজারদের কানেক্ট করুন!',
    addToTeamBtnAction: 'টিমে যুক্ত করুন',
    tagAsClientContactBtn: 'ক্লায়েন্ট কন্টাক্ট ট্যাগ',
    disconnectPerson: 'কানেকশন মুছুন',
    selectTeamPrompt: 'টিম নির্বাচন করুন',
    selectClientPrompt: 'ক্লায়েন্ট নির্বাচন করুন',
    confirmRemovePerson: 'আপনি কি নিশ্চিত যে এই ব্যক্তিকে আপনার পিপল লিস্ট থেকে বাদ দিতে চান?',

    // My Team
    teamTitle: 'আমার টিম',
    teamSubtitle: 'সহকর্মীদের যুক্ত করুন, একাধিক টিম পরিচালনা করুন ও রিকোয়েস্ট এক্সেপ্ট করুন।',
    teamMembersTab: 'টিম সদস্যবৃন্দ',
    teamRequestsTab: 'টিম রিকোয়েস্ট',
    searchMembersPlaceholder: 'ইউজারনেম দিয়ে নতুন সদস্য খুঁজুন...',
    searchBtn: 'সার্চ',
    searching: 'খোঁজা হচ্ছে...',
    noUserFound: 'কোনো ইউজার পাওয়া যায়নি।',
    addToTeamBtn: 'টিমে যুক্ত করুন',
    removeMember: 'টিম থেকে বাদ দিন',
    incomingRequestsTitle: 'ইনকামিং টিম রিকোয়েস্ট',
    noPendingRequests: 'কোনো নতুন টিম ইনভাইটেশন পেন্ডিং নেই।',
    accept: 'গ্রহণ করুন',
    reject: 'বাতিল',
    createTeamBtn: 'নতুন টিম তৈরি করুন',
    createTeamTitle: 'নতুন টিম তৈরি করুন',
    teamNameLabel: 'টিমের নাম',
    teamNamePlaceholder: 'যেমন: ডেভলপমেন্ট স্কোয়াড, খামার টিম...',
    activeTeamBadge: 'সক্রিয় টিম',
    allTeamsTitle: 'আমার টিমসমূহ',
    deleteTeamConfirm: 'আপনি কি নিশ্চিত যে এই টিমটি মুছে ফেলতে চান?',
    leaveTeamConfirm: 'আপনি কি নিশ্চিত যে এই টিমটি ত্যাগ করতে চান?',
    getGeminiKeyBtn: 'Gemini API Key নিন',
    geminiKeyHelp: 'Google AI Studio থেকে ফ্রিতে সরাসরি নিজস্ব API Key তৈরি করে নিন।',

    // Community
    communityTitle: 'গ্লোবাল কমিউনিটি চ্যাট',
    communitySubtitle: 'সব ব্যবহারকারীর উন্মুক্ত আলোচনা ও সরাসরি P2P ফাইল শেয়ারিং',
    livePeers: '● লাইভ',
    zeroServerBadge: 'সার্ভার খরচ শূন্য (P2P ট্রান্সফার)',
    p2pShared: 'P2P শেয়ার করেছেন:',
    saveFile: 'সেভ করুন',
    writeMessagePlaceholder: 'কমিউনিটিতে মেসেজ লিখুন...',

    // Client Dictionary
    clientDictionaryTitle: 'ক্লায়েন্ট ডিকশনারি',
    clientDictionarySubtitle: 'ক্লায়েন্টদের তথ্য সংরক্ষণ করুন ও কাজের হিসেব রাখুন।',
    addClientBtn: 'নতুন ক্লায়েন্ট যোগ করুন',
    clientListTitle: 'ক্লায়েন্ট সমূহ',
    noClientsYet: 'কোনো ক্লায়েন্ট যুক্ত করা হয়নি।',
    clientContact: 'যোগাযোগ:',
    clientPhone: 'ফোন:',
    clientEmail: 'ইমেইল:',
    clientNotes: 'নোট:',
    clientTasksTitle: 'এই ক্লায়েন্টের টাস্ক সমূহ',
    noTasksForClient: 'এই ক্লায়েন্টের সাথে এখনও কোনো কাজ ট্যাগ করা হয়নি।',
    editClientTitle: 'ক্লায়েন্ট তথ্য এডিট',
    clientNameLabel: 'ক্লায়েন্টের নাম *',
    clientCompanyLabel: 'প্রতিষ্ঠান বা কোম্পানি',
    contactPersonLabel: 'যোগাযোগ ব্যক্তি',
    phoneLabel: 'ফোন নম্বর',
    emailLabel: 'ইমেইল',
    notesLabel: 'নোট বা নির্দেশনা',
    saveClientBtn: 'সেভ করুন',

    // Task Directory
    taskDirectoryTitle: 'টাস্ক ডিরেক্টরি',
    taskDirectorySubtitle: 'ব্যক্তিগত ও টিমভিত্তিক টাস্কের ধরন আলাদাভাবে পরিচালনা করুন।',
    personalTaskTypes: 'ব্যক্তিগত টাস্ক টাইপ',
    teamTaskTypes: 'টিম টাস্ক টাইপ',
    addTaskTypeTitle: 'নতুন টাস্ক টাইপ যোগ করুন',
    editTaskTypeTitle: 'টাস্ক টাইপ এডিট করুন',
    taskTypeNameLabel: 'টাস্ক টাইপের নাম *',
    taskTypeNamePlaceholder: 'যেমন: ইউআই ডিজাইন, বাগ ফিক্স, বা খামার পরিদর্শন',
    scopeLabel: 'ওয়ার্কস্পেস স্কোপ',
    saveTaskTypeBtn: 'টাস্ক টাইপ সেভ করুন',
    updateTaskTypeBtn: 'আপডেট করুন',
    cancelEdit: 'বাতিল',
    currentTaskTypesTitle: 'বর্তমান টাস্ক টাইপসমূহ',
    noTaskTypesYet: 'কোনো টাস্ক টাইপ তৈরি করা হয়নি।',

    // Settings & Profile
    settingsTitle: 'সফটওয়্যার সেটিংস ও প্রোফাইল',
    generalThemeTab: 'সাধারণ সেটিংস',
    profileInfoTab: 'প্রোফাইল তথ্য',
    geminiKeyTab: 'Gemini AI কী',
    themeLabel: 'সফটওয়্যার থিম',
    darkTheme: 'ডার্ক মোড',
    grayTheme: 'গ্রে স্লেট',
    lightTheme: 'লাইট ক্লিন',
    localStorageLabel: 'ফাইল স্টোরেজ ফোল্ডার (PC / ডিভাইস ডিরেক্টরি)',
    localStorageDesc: 'হোস্টিং খরচ শূন্য রাখতে সব ফাইল সরাসরি আপনার পিসির এই ফোল্ডারে সেভ থাকবে।',
    browseBtn: 'ব্রাউজ',
    accountCredsTitle: 'ইউজারনেম ও পাসওয়ার্ড পরিবর্তন',
    usernameLabel: 'ইউজারনেম',
    newPasswordLabel: 'নতুন পাসওয়ার্ড (ঐচ্ছিক)',
    saveSettingsBtn: 'সেটিংস সেভ করুন',
    savedSuccess: 'সেটিংস সফলভাবে সংরক্ষিত হয়েছে!',
    fullNameLabel: 'পুরো নাম',
    avatarLabel: 'প্রোফাইল ছবি / অবতার',
    bioLabel: 'বায়ো বা পরিচয়',
    linksLabel: 'লিংক ও সোশ্যাল প্রোফাইল (কমা দিয়ে আলাদা করুন)',
    updateProfileBtn: 'প্রোফাইল আপডেট করুন',
    profileUpdatedSuccess: 'প্রোফাইল সফলভাবে আপডেট হয়েছে!',
    logout: 'লগআউট',
    settingsAndProfile: 'সেটিংস ও প্রোফাইল'
  },
  en: {
    // Brand & App
    appName: 'Tasker',
    appBadge: 'Universal',
    searchPlaceholder: 'Search tasks...',
    aiChat: 'AI Chat',
    storageMode: 'Storage Mode',
    zeroCostStorage: '● Local & P2P ($0 Cost)',
    storageDesc: 'Files are saved locally on your device, not on cloud servers.',

    // Sidebar
    mainNavigation: 'Main Menu',
    workDashboard: 'Work Dashboard',
    currentWorkspace: 'Current Workspace',
    calendarView: 'Calendar View',
    calendarSub: 'Date-to-Date Workflow',
    people: 'People',
    peopleSub: 'Contacts & Network',
    myTeam: 'My Team',
    teamSub: 'Collaboration & Requests',
    community: 'Community',
    communitySub: 'Global Network Chat',
    clientDictionary: 'Client Dictionary',
    clientSub: 'Clients & Work Logs',
    taskDirectory: 'Task Directory',
    taskDirectorySub: 'Manage Personal & Team Task Types',

    // Dashboard
    personal: 'Personal',
    team: 'Team',
    selectTeam: 'Select Team:',
    allTeamsOption: 'All Teams',
    kanban: 'Kanban',
    list: 'List',
    filterBy: 'Filter:',
    allClients: 'All Clients',
    allCategories: 'All Task Types',
    allTaskTypes: 'All Task Types',
    reset: 'Reset',
    newTask: 'New Task',
    todo: 'To Do',
    inProgress: 'In Progress',
    submitForReview: 'Submit for Review',
    approved: 'Approved',
    done: 'Done',
    startWork: 'Start Work',
    markDone: 'Done',
    submitReviewBtn: 'Submit Review',
    approveBtn: 'Approve',
    carryForward: 'Carry Forward',
    sendBackTodo: 'Send back to To Do',
    sendBackInProgress: 'Send back to In Progress',
    editTask: 'Edit Task Details',
    deleteTask: 'Delete Task',
    moveToTeam: 'Move to Team',
    moveToPersonal: 'Move to Personal',
    noTasksInCol: 'No tasks in this column',
    noTasksFound: 'No tasks found. Click "New Task" to create one.',
    taskTitleCol: 'Task Title',
    clientCategoryCol: 'Client / Task Type',
    clientTaskTypeCol: 'Client / Task Type',
    dateCol: 'Date',
    priorityCol: 'Priority',
    actionsCol: 'Actions',
    selectCarryForwardDate: 'Select new scheduled date:',

    // Task Modal
    createTaskModalTitle: 'Create New Task',
    editTaskModalTitle: 'Edit Task Details',
    taskTitleLabel: 'Task Title *',
    taskTitlePlaceholder: 'What needs to be done? Type or hold mic to record...',
    scheduledDateLabel: 'Scheduled Date',
    workspaceLabel: 'Workspace',
    teamLabel: 'Select Team',
    briefLabel: 'Brief Description',
    briefPlaceholder: 'Add detailed instructions or client notes...',
    sourceLinkLabel: 'Source Link (Figma / GitHub / Link)',
    clientTagLabel: 'Tag Client',
    noClientOption: '-- No Client --',
    categoryLabel: 'Task Type',
    taskTypeLabel: 'Task Type',
    noCategoryOption: '-- General / None --',
    noTaskTypeOption: '-- General / None --',
    priorityLabel: 'Priority',
    priorityLow: 'Low',
    priorityMedium: 'Medium',
    priorityHigh: 'High',
    priorityUrgent: 'Urgent',
    fileAttachLabel: 'Attach Files & Images (Saved locally on PC)',
    cancel: 'Cancel',
    saveTask: 'Save Task',
    updateTask: 'Update Task',
    voiceHoldText: 'Hold to Talk',
    voiceRecording: 'Recording...',
    voiceReleaseDone: 'Release when done',
    slideCancel: 'Slide to cancel',

    // Calendar
    today: 'Today',
    todayBadge: 'Today',
    sun: 'Sun', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat',
    completedCount: 'Done',
    pendingCount: 'Pending',
    pastHistoryTitle: 'Past Work History',
    todayTitle: "Today's Work",
    futurePlanTitle: 'Future Planning',
    addTaskOnDate: 'Add Task',
    // People & Contacts
    peopleTitle: 'People & Connected Network',
    peopleSubtitle: 'Search global users, connect, add to teams, or tag as Client Contact Person.',
    searchPeoplePlaceholder: 'Search global users by name or username to connect...',
    connectedPeopleTitle: 'Connected People',
    noConnectedPeople: 'No connected users yet. Search above to connect with people!',
    addToTeamBtnAction: 'Add to Team',
    tagAsClientContactBtn: 'Tag as Client Contact',
    disconnectPerson: 'Disconnect',
    selectTeamPrompt: 'Select Team',
    selectClientPrompt: 'Select Client',
    confirmRemovePerson: 'Are you sure you want to remove this person from your connected network?',

    // My Team
    teamTitle: 'My Teams',
    teamSubtitle: 'Collaborate with teammates, manage multiple teams, and workspace invites.',
    teamMembersTab: 'Team Members',
    teamRequestsTab: 'Team Requests',
    searchMembersPlaceholder: 'Search users by username to invite...',
    searchBtn: 'Search',
    searching: 'Searching...',
    noUserFound: 'No user found.',
    addToTeamBtn: 'Add to Team',
    removeMember: 'Remove Member',
    incomingRequestsTitle: 'Incoming Team Requests',
    noPendingRequests: 'No pending team invites.',
    accept: 'Accept',
    reject: 'Reject',
    createTeamBtn: 'Create New Team',
    createTeamTitle: 'Create New Team',
    teamNameLabel: 'Team Name',
    teamNamePlaceholder: 'e.g. Core Engineering, Farm Operations...',
    activeTeamBadge: 'Active Team',
    allTeamsTitle: 'My Teams',
    deleteTeamConfirm: 'Are you sure you want to delete this team?',
    leaveTeamConfirm: 'Are you sure you want to leave this team?',
    getGeminiKeyBtn: 'Get Gemini API Key',
    geminiKeyHelp: 'Get your free Gemini API key in seconds from Google AI Studio.',

    // Community
    communityTitle: 'Global Community Chat',
    communitySubtitle: 'Open discussions with P2P direct media transfer',
    livePeers: '● Live',
    zeroServerBadge: 'Zero Cloud Storage (P2P Transfer)',
    p2pShared: 'Shared via P2P:',
    saveFile: 'Download',
    writeMessagePlaceholder: 'Write a community message...',

    // Client Dictionary
    clientDictionaryTitle: 'Client Dictionary',
    clientDictionarySubtitle: 'Manage client directory and view project work logs.',
    addClientBtn: 'Add New Client',
    clientListTitle: 'Clients',
    noClientsYet: 'No clients added yet.',
    clientContact: 'Contact:',
    clientPhone: 'Phone:',
    clientEmail: 'Email:',
    clientNotes: 'Notes:',
    clientTasksTitle: 'Tasks for this Client',
    noTasksForClient: 'No tasks associated with this client yet.',
    editClientTitle: 'Edit Client Details',
    clientNameLabel: 'Client Name *',
    clientCompanyLabel: 'Company / Organization',
    contactPersonLabel: 'Contact Person',
    phoneLabel: 'Phone Number',
    emailLabel: 'Email',
    notesLabel: 'Notes or Guidelines',
    saveClientBtn: 'Save Client',

    // Task Directory
    taskDirectoryTitle: 'Task Directory',
    taskDirectorySubtitle: 'Manage personal and team task types separately without unnecessary clutter.',
    personalTaskTypes: 'Personal Task Types',
    teamTaskTypes: 'Team Task Types',
    addTaskTypeTitle: 'Add New Task Type',
    editTaskTypeTitle: 'Edit Task Type',
    taskTypeNameLabel: 'Task Type Name *',
    taskTypeNamePlaceholder: 'e.g. Code Review, Bug Fix, Farm Logistics, or Design',
    scopeLabel: 'Workspace Scope',
    saveTaskTypeBtn: 'Save Task Type',
    updateTaskTypeBtn: 'Update Task Type',
    cancelEdit: 'Cancel',
    currentTaskTypesTitle: 'Current Task Types',
    noTaskTypesYet: 'No task types created yet.',

    // Settings & Profile
    settingsTitle: 'Settings & Profile',
    generalThemeTab: 'General',
    profileInfoTab: 'Profile Info',
    geminiKeyTab: 'Gemini AI Key',
    themeLabel: 'Software Theme',
    darkTheme: 'Dark Mode',
    grayTheme: 'Gray Slate',
    lightTheme: 'Light Clean',
    localStorageLabel: 'File Storage Directory (PC / Device Local Path)',
    localStorageDesc: 'All files & images are stored directly in this PC directory to eliminate hosting fees.',
    browseBtn: 'Browse',
    accountCredsTitle: 'Account Credentials',
    usernameLabel: 'Username',
    newPasswordLabel: 'New Password (Optional)',
    saveSettingsBtn: 'Save Settings',
    savedSuccess: 'Settings saved successfully!',
    fullNameLabel: 'Full Name',
    avatarLabel: 'Profile Avatar URL or Emoji',
    bioLabel: 'Bio or Role',
    linksLabel: 'Links & Social Profiles (Comma separated)',
    updateProfileBtn: 'Update Profile',
    profileUpdatedSuccess: 'Profile updated successfully!',
    logout: 'Log Out',
    settingsAndProfile: 'Settings & Profile'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('tasker_language') || 'en';
  });

  const toggleLanguage = () => {
    const next = lang === 'bn' ? 'en' : 'bn';
    setLang(next);
    localStorage.setItem('tasker_language', next);
  };

  const setLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('tasker_language', newLang);
  };

  const t = translations[lang] || translations.bn;

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
