import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

export const translations = {
  bn: {
    // Brand & App
    appName: 'Tasker',
    appBadge: 'সার্বজনীন',
    searchPlaceholder: 'টাস্ক সার্চ করুন...',
    aiChat: 'AI চ্যাট',
    storageMode: 'স্টোরেজ মোড',
    zeroCostStorage: '● লোকাল ও P2P (খরচ শূন্য)',
    storageDesc: 'ফাইল ক্লাউডে নয়, আপনার পিসিতে নিরাপদে সংরক্ষিত।',

    // Sidebar
    mainNavigation: 'প্রধান মেনু',
    workDashboard: 'ওয়ার্ক ড্যাশবোর্ড',
    currentWorkspace: 'বর্তমান কাজের বোর্ড',
    calendarView: 'ক্যালেন্ডার ভিউ',
    calendarSub: 'তারিখভিত্তিক কাজের হিসাব',
    myTeam: 'আমার টিম',
    teamSub: 'সহযোগিতা ও রিকোয়েস্ট',
    community: 'কমিউনিটি',
    communitySub: 'গ্লোবাল নেটওয়ার্ক চ্যাট',
    clientDictionary: 'ক্লায়েন্ট ডিকশনারি',
    clientSub: 'ক্লায়েন্ট ও কাজের হিসাব',
    taskDirectory: 'টাস্ক ডিরেক্টরি',
    taskDirectorySub: 'টাস্কের ধরন ও ক্যাটাগরি',

    // Dashboard
    personal: 'ব্যক্তিগত',
    team: 'টিম',
    kanban: 'কানবান',
    list: 'লিস্ট',
    filterBy: 'ফিল্টার:',
    allClients: 'সকল ক্লায়েন্ট',
    allCategories: 'সকল ক্যাটাগরি',
    reset: 'রিসেট',
    newTask: 'নতুন টাস্ক',
    todo: 'করতে হবে (To Do)',
    inProgress: 'চলমান (In Progress)',
    submitForReview: 'রিভিউ জমা (Submit for Review)',
    approved: 'অনুমোদিত (Approved)',
    done: 'সম্পন্ন (Done)',
    startWork: 'কাজ শুরু করুন',
    markDone: 'সম্পন্ন',
    submitReviewBtn: 'রিভিউতে পাঠান',
    approveBtn: 'অনুমোদন দিন',
    carryForward: 'পরবর্তী তারিখে নিন (Carry Forward)',
    sendBackTodo: 'To Do-তে ফেরত পাঠান',
    sendBackInProgress: 'In Progress-এ ফেরত পাঠান',
    editTask: 'টাস্ক এডিট করুন',
    deleteTask: 'টাস্ক মুছুন',
    moveToTeam: 'টিমে নিন',
    moveToPersonal: 'ব্যক্তিগতে নিন',
    noTasksInCol: 'এই কলামে কোনো কাজ নেই',
    noTasksFound: 'কোনো টাস্ক পাওয়া যায়নি। "নতুন টাস্ক" বাটনে ক্লিক করুন।',
    taskTitleCol: 'কাজের নাম',
    clientCategoryCol: 'ক্লায়েন্ট / ক্যাটাগরি',
    dateCol: 'তারিখ',
    priorityCol: 'অগ্রাধিকার',
    actionsCol: 'অ্যাকশন',
    selectCarryForwardDate: 'কাজের নতুন তারিখ নির্বাচন করুন:',

    // Task Modal
    createTaskModalTitle: 'নতুন টাস্ক তৈরি',
    editTaskModalTitle: 'টাস্ক এডিট করুন',
    taskTitleLabel: 'টাস্কের শিরোনাম *',
    taskTitlePlaceholder: 'কী কাজ করতে হবে লিখুন বা ভয়েস দিন...',
    scheduledDateLabel: 'কাজের তারিখ',
    workspaceLabel: 'ওয়ার্কস্পেস',
    briefLabel: 'বিস্তারিত বিবরণ',
    briefPlaceholder: 'টাস্কের বিস্তারিত নোট বা নির্দেশনা লিখুন...',
    sourceLinkLabel: 'সোর্স লিংক (Figma / GitHub / Link)',
    clientTagLabel: 'ক্লায়েন্ট ট্যাগ করুন',
    noClientOption: '-- কোনো ক্লায়েন্ট নেই --',
    categoryLabel: 'ক্যাটাগরি',
    noCategoryOption: '-- সাধারণ --',
    priorityLabel: 'অগ্রাধিকার',
    priorityLow: 'স্বাভাবিক (Low)',
    priorityMedium: 'সাধারণ (Medium)',
    priorityHigh: 'গুরুত্বপূর্ণ (High)',
    priorityUrgent: 'জরুরি (Urgent)',
    fileAttachLabel: 'ফাইল ও ছবি যুক্ত করুন (লোকাল পিসিতে সংরক্ষিত হবে)',
    cancel: 'বাতিল',
    saveTask: 'টাস্ক সেভ করুন',
    updateTask: 'টাস্ক আপডেট করুন',
    voiceHoldText: 'চেপে ধরে কথা বলুন',
    voiceRecording: 'রেকর্ড হচ্ছে...',
    voiceReleaseDone: 'ছেড়ে দিলে সম্পন্ন হবে',
    slideCancel: 'বাতিল করতে স্লাইড করুন',

    // Calendar
    today: 'আজকের দিন',
    todayBadge: 'আজ',
    sun: 'রবি', mon: 'সোম', tue: 'মঙ্গল', wed: 'বুধ', thu: 'বৃহঃ', fri: 'শুক্র', sat: 'শনি',
    completedCount: 'সম্পন্ন',
    pendingCount: 'বাকি',
    pastHistoryTitle: 'পূর্বের কাজের হিস্ট্রি',
    todayTitle: 'আজকের কাজ',
    futurePlanTitle: 'ভবিষ্যতের পরিকল্পনা',
    addTaskOnDate: 'কাজ যোগ করুন',
    noTasksOnDate: 'এই তারিখে কোনো কাজ নির্ধারিত নেই',

    // My Team
    teamTitle: 'আমার টিম',
    teamSubtitle: 'সহকর্মীদের যুক্ত করুন ও টিম রিকোয়েস্ট পরিচালনা করুন।',
    teamMembersTab: 'টিম সদস্যবৃন্দ',
    teamRequestsTab: 'টিম রিকোয়েস্ট',
    searchMembersPlaceholder: 'ইউজারনেম দিয়ে নতুন সদস্য খুঁজুন...',
    searchBtn: 'সার্চ',
    searching: 'খোঁজা হচ্ছে...',
    noUserFound: 'কোনো ইউজার পাওয়া যায়নি।',
    addToTeamBtn: 'টিমে যুক্ত করুন',
    removeMember: 'টিম থেকে বাদ দিন',
    incomingRequestsTitle: 'ইনকামিং টিম রিকোয়েস্ট',
    noPendingRequests: 'কোনো নতুন টিম ইনভাইটেশন পেন্ডিং নেই।',
    accept: 'গ্রহণ করুন',
    reject: 'বাতিল',

    // Community
    communityTitle: 'গ্লোবাল কমিউনিটি চ্যাট',
    communitySubtitle: 'সব ব্যবহারকারীর উন্মুক্ত আলোচনা ও সরাসরি P2P ফাইল শেয়ারিং',
    livePeers: '● লাইভ',
    zeroServerBadge: 'সার্ভার খরচ শূন্য (P2P ট্রান্সফার)',
    p2pShared: 'P2P শেয়ার করেছেন:',
    saveFile: 'সেভ করুন',
    writeMessagePlaceholder: 'কমিউনিটিতে মেসেজ লিখুন...',

    // Client Dictionary
    clientDictionaryTitle: 'ক্লায়েন্ট ডিকশনারি',
    clientDictionarySubtitle: 'ক্লায়েন্টদের তথ্য সংরক্ষণ করুন ও কাজের হিসেব রাখুন।',
    addClientBtn: 'নতুন ক্লায়েন্ট যোগ করুন',
    clientListTitle: 'ক্লায়েন্ট সমূহ',
    noClientsYet: 'কোনো ক্লায়েন্ট যুক্ত করা হয়নি।',
    clientContact: 'যোগাযোগ:',
    clientPhone: 'ফোন:',
    clientEmail: 'ইমেইল:',
    clientNotes: 'নোট:',
    clientTasksTitle: 'এই ক্লায়েন্টের টাস্ক সমূহ',
    noTasksForClient: 'এই ক্লায়েন্টের সাথে এখনও কোনো কাজ ট্যাগ করা হয়নি।',
    editClientTitle: 'ক্লায়েন্ট তথ্য এডিট',
    clientNameLabel: 'ক্লায়েন্টের নাম *',
    clientCompanyLabel: 'প্রতিষ্ঠান বা কোম্পানি',
    contactPersonLabel: 'যোগাযোগ ব্যক্তি',
    phoneLabel: 'ফোন নম্বর',
    emailLabel: 'ইমেইল',
    notesLabel: 'নোট বা নির্দেশনা',
    saveClientBtn: 'সেভ করুন',

    // Task Directory
    taskDirectoryTitle: 'টাস্ক ডিরেক্টরি',
    taskDirectorySubtitle: 'আপনার পছন্দমতো টাস্কের ধরন ও ক্যাটাগরি তৈরি করুন।',
    addCategoryTitle: 'নতুন ক্যাটাগরি যোগ করুন',
    editCategoryTitle: 'ক্যাটাগরি এডিট করুন',
    categoryNameLabel: 'ক্যাটাগরি বা টাস্কের ধরন *',
    categoryNamePlaceholder: 'যেমন: ঘর ঝাড়ু, ইউআই ডিজাইন, বা বাগ ফিক্স',
    colorTagLabel: 'রঙের ব্যাজ',
    saveCategoryBtn: 'ক্যাটাগরি সেভ করুন',
    updateCategoryBtn: 'আপডেট করুন',
    cancelEdit: 'বাতিল',
    currentCategoriesTitle: 'বর্তমান ক্যাটাগরি সমূহ',
    noCategoriesYet: 'কোনো ক্যাটাগরি তৈরি করা হয়নি।',

    // Settings & Profile
    settingsTitle: 'সফটওয়্যার সেটিংস ও প্রোফাইল',
    generalThemeTab: 'সাধারণ ও থিম',
    profileInfoTab: 'প্রোফাইল তথ্য',
    geminiKeyTab: 'Gemini AI কী',
    themeLabel: 'সফটওয়্যার থিম',
    darkTheme: 'ডার্ক মোড',
    grayTheme: 'গ্রে স্লেট',
    lightTheme: 'লাইট ক্লিন',
    localStorageLabel: 'ফাইল স্টোরেজ ফোল্ডার (PC / ডিভাইস ডিরেক্টরি)',
    localStorageDesc: 'হোস্টিং খরচ শূন্য রাখতে সব ফাইল সরাসরি আপনার পিসির এই ফোল্ডারে সেভ থাকবে।',
    browseBtn: 'ব্রাউজ',
    accountCredsTitle: 'ইউজারনেম ও পাসওয়ার্ড পরিবর্তন',
    usernameLabel: 'ইউজারনেম',
    newPasswordLabel: 'নতুন পাসওয়ার্ড (ঐচ্ছিক)',
    saveSettingsBtn: 'সেটিংস সেভ করুন',
    savedSuccess: 'সেটিংস সফলভাবে সংরক্ষিত হয়েছে!',
    fullNameLabel: 'পুরো নাম',
    avatarLabel: 'প্রোফাইল ছবি / অবতার',
    bioLabel: 'বায়ো বা পরিচয়',
    linksLabel: 'লিংক ও সোশ্যাল প্রোফাইল (কমা দিয়ে আলাদা করুন)',
    updateProfileBtn: 'প্রোফাইল আপডেট করুন',
    profileUpdatedSuccess: 'প্রোফাইল সফলভাবে আপডেট হয়েছে!',
    logout: 'লগআউট',
    settingsAndProfile: 'সেটিংস ও প্রোফাইল'
  },
  en: {
    // Brand & App
    appName: 'Tasker',
    appBadge: 'Universal',
    searchPlaceholder: 'Search tasks...',
    aiChat: 'AI Chat',
    storageMode: 'Storage Mode',
    zeroCostStorage: '● Local & P2P ($0 Cost)',
    storageDesc: 'Files are saved locally on your device, not on cloud servers.',

    // Sidebar
    mainNavigation: 'Main Menu',
    workDashboard: 'Work Dashboard',
    currentWorkspace: 'Current Workspace',
    calendarView: 'Calendar View',
    calendarSub: 'Date-to-Date Workflow',
    myTeam: 'My Team',
    teamSub: 'Collaboration & Requests',
    community: 'Community',
    communitySub: 'Global Network Chat',
    clientDictionary: 'Client Dictionary',
    clientSub: 'Clients & Work Logs',
    taskDirectory: 'Task Directory',
    taskDirectorySub: 'Task Types & Categories',

    // Dashboard
    personal: 'Personal',
    team: 'Team',
    kanban: 'Kanban',
    list: 'List',
    filterBy: 'Filter:',
    allClients: 'All Clients',
    allCategories: 'All Categories',
    reset: 'Reset',
    newTask: 'New Task',
    todo: 'To Do',
    inProgress: 'In Progress',
    submitForReview: 'Submit for Review',
    approved: 'Approved',
    done: 'Done',
    startWork: 'Start Work',
    markDone: 'Done',
    submitReviewBtn: 'Submit Review',
    approveBtn: 'Approve',
    carryForward: 'Carry Forward',
    sendBackTodo: 'Send back to To Do',
    sendBackInProgress: 'Send back to In Progress',
    editTask: 'Edit Task Details',
    deleteTask: 'Delete Task',
    moveToTeam: 'Move to Team',
    moveToPersonal: 'Move to Personal',
    noTasksInCol: 'No tasks in this column',
    noTasksFound: 'No tasks found. Click "New Task" to create one.',
    taskTitleCol: 'Task Title',
    clientCategoryCol: 'Client / Category',
    dateCol: 'Date',
    priorityCol: 'Priority',
    actionsCol: 'Actions',
    selectCarryForwardDate: 'Select new scheduled date:',

    // Task Modal
    createTaskModalTitle: 'Create New Task',
    editTaskModalTitle: 'Edit Task Details',
    taskTitleLabel: 'Task Title *',
    taskTitlePlaceholder: 'What needs to be done? Type or hold mic to record...',
    scheduledDateLabel: 'Scheduled Date',
    workspaceLabel: 'Workspace',
    briefLabel: 'Brief Description',
    briefPlaceholder: 'Add detailed instructions or client notes...',
    sourceLinkLabel: 'Source Link (Figma / GitHub / Link)',
    clientTagLabel: 'Tag Client',
    noClientOption: '-- No Client --',
    categoryLabel: 'Category',
    noCategoryOption: '-- General --',
    priorityLabel: 'Priority',
    priorityLow: 'Low',
    priorityMedium: 'Medium',
    priorityHigh: 'High',
    priorityUrgent: 'Urgent',
    fileAttachLabel: 'Attach Files & Images (Saved locally on PC)',
    cancel: 'Cancel',
    saveTask: 'Save Task',
    updateTask: 'Update Task',
    voiceHoldText: 'Hold to Talk',
    voiceRecording: 'Recording...',
    voiceReleaseDone: 'Release when done',
    slideCancel: 'Slide to cancel',

    // Calendar
    today: 'Today',
    todayBadge: 'Today',
    sun: 'Sun', mon: 'Mon', tue: 'Tue', wed: 'Wed', thu: 'Thu', fri: 'Fri', sat: 'Sat',
    completedCount: 'Done',
    pendingCount: 'Pending',
    pastHistoryTitle: 'Past Work History',
    todayTitle: "Today's Work",
    futurePlanTitle: 'Future Planning',
    addTaskOnDate: 'Add Task',
    noTasksOnDate: 'No tasks scheduled for this date',

    // My Team
    teamTitle: 'My Team',
    teamSubtitle: 'Collaborate with teammates and manage workspace invites.',
    teamMembersTab: 'Team Members',
    teamRequestsTab: 'Team Requests',
    searchMembersPlaceholder: 'Search users by username to invite...',
    searchBtn: 'Search',
    searching: 'Searching...',
    noUserFound: 'No user found.',
    addToTeamBtn: 'Add to Team',
    removeMember: 'Remove Member',
    incomingRequestsTitle: 'Incoming Team Requests',
    noPendingRequests: 'No pending team invites.',
    accept: 'Accept',
    reject: 'Reject',

    // Community
    communityTitle: 'Global Community Chat',
    communitySubtitle: 'Open discussions with P2P direct media transfer',
    livePeers: '● Live',
    zeroServerBadge: 'Zero Cloud Storage (P2P Transfer)',
    p2pShared: 'Shared via P2P:',
    saveFile: 'Download',
    writeMessagePlaceholder: 'Write a community message...',

    // Client Dictionary
    clientDictionaryTitle: 'Client Dictionary',
    clientDictionarySubtitle: 'Manage client directory and view project work logs.',
    addClientBtn: 'Add New Client',
    clientListTitle: 'Clients',
    noClientsYet: 'No clients added yet.',
    clientContact: 'Contact:',
    clientPhone: 'Phone:',
    clientEmail: 'Email:',
    clientNotes: 'Notes:',
    clientTasksTitle: 'Tasks for this Client',
    noTasksForClient: 'No tasks associated with this client yet.',
    editClientTitle: 'Edit Client Details',
    clientNameLabel: 'Client Name *',
    clientCompanyLabel: 'Company / Organization',
    contactPersonLabel: 'Contact Person',
    phoneLabel: 'Phone Number',
    emailLabel: 'Email',
    notesLabel: 'Notes or Guidelines',
    saveClientBtn: 'Save Client',

    // Task Directory
    taskDirectoryTitle: 'Task Directory',
    taskDirectorySubtitle: 'Define custom task categories and badges.',
    addCategoryTitle: 'Add New Category',
    editCategoryTitle: 'Edit Category',
    categoryNameLabel: 'Category / Task Type Name *',
    categoryNamePlaceholder: 'e.g. Room Cleaning, UI Design, or Bug Fix',
    colorTagLabel: 'Color Badge',
    saveCategoryBtn: 'Save Category',
    updateCategoryBtn: 'Update Category',
    cancelEdit: 'Cancel',
    currentCategoriesTitle: 'Current Categories',
    noCategoriesYet: 'No categories created yet.',

    // Settings & Profile
    settingsTitle: 'Settings & Profile',
    generalThemeTab: 'General & Theme',
    profileInfoTab: 'Profile Info',
    geminiKeyTab: 'Gemini AI Key',
    themeLabel: 'Software Theme',
    darkTheme: 'Dark Mode',
    grayTheme: 'Gray Slate',
    lightTheme: 'Light Clean',
    localStorageLabel: 'File Storage Directory (PC / Device Local Path)',
    localStorageDesc: 'All files & images are stored directly in this PC directory to eliminate hosting fees.',
    browseBtn: 'Browse',
    accountCredsTitle: 'Account Credentials',
    usernameLabel: 'Username',
    newPasswordLabel: 'New Password (Optional)',
    saveSettingsBtn: 'Save Settings',
    savedSuccess: 'Settings saved successfully!',
    fullNameLabel: 'Full Name',
    avatarLabel: 'Profile Avatar URL or Emoji',
    bioLabel: 'Bio or Role',
    linksLabel: 'Links & Social Profiles (Comma separated)',
    updateProfileBtn: 'Update Profile',
    profileUpdatedSuccess: 'Profile updated successfully!',
    logout: 'Log Out',
    settingsAndProfile: 'Settings & Profile'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('tasker_language') || 'bn';
  });

  const toggleLanguage = () => {
    const next = lang === 'bn' ? 'en' : 'bn';
    setLang(next);
    localStorage.setItem('tasker_language', next);
  };

  const setLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('tasker_language', newLang);
  };

  const t = translations[lang] || translations.bn;

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
